### ISSUE TITLE
webhook panic when read v1 kv which created by startupSecrets

### ISSUE THREAD

**Issue by hulucc** [banzaicloud/bank-vaults#1374]
```
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook 2021/07/01 03:23:03 http: panic serving 10.136.90.7:39658: interface conversion: interface {} is nil, not map[string]interface {}
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook goroutine 256 [running]:
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook net/http.(*conn).serve.func1(0xc00057b7c0)
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook    /usr/local/go/src/net/http/server.go:1824 +0x153
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook panic(0x1e43360, 0xc0006ad0b0)
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook    /usr/local/go/src/runtime/panic.go:971 +0x499
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook github.com/banzaicloud/bank-vaults/internal/injector.SecretInjector.readVaultPath(0x0, 0x0, 0x0, 0x0, 0x0, 0xc000a02b90, 0x0, 0x0, 0x2467db0, 0xc000319ce0, ...)
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook    /build/internal/injector/injector.go:281 +0xda5
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook github.com/banzaicloud/bank-vaults/internal/injector.SecretInjector.InjectSecretsFromVault(0x0, 0x0, 0x0, 0x0, 0x0, 0xc000a02b90, 0x0, 0x0, 0x2467db0, 0xc000319ce0, ...)
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook    /build/internal/injector/injector.go:154 +0xfd8
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook main.getDataFromVault(0xc00068ff80, 0xc000a02b90, 0xc00004209b, 0x18, 0x20f0128, 0x3, 0xc00004600b, 0x7, 0x20f8e12, 0xa, ...)
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook    /build/cmd/vault-secrets-webhook/common.go:42 +0x1b5
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook main.(*mutatingWebhook).mutateConfigMapData(0xc00032fbc0, 0xc00034d040, 0xc00068ff80, 0xc000a02b90, 0xc00004209b, 0x18, 0x20f0128, 0x3, 0xc00004600b, 0x7, ...)
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook    /build/cmd/vault-secrets-webhook/configmap.go:94 +0x93

vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook main.(*mutatingWebhook).mutateConfigMap(0xc00032fbc0, 0xc00034d040, 0xc00004209b, 0x18, 0x20f0128, 0x3, 0xc00004600b, 0x7, 0x20f8e12, 0xa, ...)
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook    /build/cmd/vault-secrets-webhook/configmap.go:71 +0x358
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook main.(*mutatingWebhook).vaultSecretsMutator(0xc00032fbc0, 0x2442710, 0xc000c04270, 0xc00017a0f0, 0x246a778, 0xc00034d040, 0xe8, 0x7f31a4ad15b8, 0xf0)
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook    /build/cmd/vault-secrets-webhook/main.go:450 +0x4b8
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook github.com/slok/kubewebhook/v2/pkg/webhook/mutating.MutatorFunc.Mutate(0xc0004452d0, 0x2442710, 0xc000c04270, 0xc00017a0f0, 0x246a778, 0xc00034d040, 0x20c8120, 0x246a778, 0x1fb5c40)
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook    /go/pkg/mod/github.com/slok/kubewebhook/v2@v2.1.0/pkg/webhook/mutating/mutator.go:45 +0x58
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook github.com/slok/kubewebhook/v2/pkg/webhook/mutating.mutatingWebhook.mutatingAdmissionReview(0x210e5c5, 0x17, 0x2409200, 0xc0002c0f20, 0x2409220, 0xc0004452d0, 0x210e5c5, 0x17, 0x246a778, 0xc00034c280, ...)
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook    /go/pkg/mod/github.com/slok/kubewebhook/v2@v2.1.0/pkg/webhook/mutating/webhook.go:116 +0xe6
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook github.com/slok/kubewebhook/v2/pkg/webhook/mutating.mutatingWebhook.Review(0x210e5c5, 0x17, 0x2409200, 0xc0002c0f20, 0x2409220, 0xc0004452d0, 0x210e5c5, 0x17, 0x246a778, 0xc00034c280, ...)
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook    /go/pkg/mod/github.com/slok/kubewebhook/v2@v2.1.0/pkg/webhook/mutating/webhook.go:104 +0x278
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook github.com/slok/kubewebhook/v2/pkg/webhook.measuredWebhook.Review(0x210e5c5, 0x17, 0x20f5fdd, 0x8, 0x2413248, 0xc00000e5d0, 0x2431bb0, 0xc0006e6900, 0x2442710, 0xc000c04270, ...)
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook    /go/pkg/mod/github.com/slok/kubewebhook/v2@v2.1.0/pkg/webhook/metrics.go:114 +0x195
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook github.com/slok/kubewebhook/v2/pkg/http.handler.ServeHTTP(0x243c5f0, 0xc00032fd80, 0x24540c8, 0xc000318850, 0x243c0b0, 0xc000834fc0, 0xc0005d3400)
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook    /go/pkg/mod/github.com/slok/kubewebhook/v2@v2.1.0/pkg/http/handler.go:129 +0x9d5
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook net/http.(*ServeMux).ServeHTTP(0xc00032fe40, 0x243c0b0, 0xc000834fc0, 0xc0005d3400)
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook    /usr/local/go/src/net/http/server.go:2448 +0x1ad
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook net/http.serverHandler.ServeHTTP(0xc000834000, 0x243c0b0, 0xc000834fc0, 0xc0005d3400)
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook    /usr/local/go/src/net/http/server.go:2887 +0xa3
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook net/http.(*conn).serve(0xc00057b7c0, 0x2442710, 0xc00053ebc0)
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook    /usr/local/go/src/net/http/server.go:1952 +0x8cd
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook created by net/http.(*Server).Serve
vault-secrets-webhook-67cc85594b-nqprl vault-secrets-webhook    /usr/local/go/src/net/http/server.go:3013 +0x39
```

**Comment by hulucc** [comment]
Solved. Should remove `data` in `startupSecrets`
