### ISSUE TITLE
Operator in crash loop: index out of range [5] with length 5

### ISSUE THREAD

**Issue by tabossert** [banzaicloud/bank-vaults#1423]
**Describe the bug**:
Operator container constantly crashing on startup with the following error
```go
{"level":"info","ts":1632155743.3829668,"logger":"controller_vault","msg":"Reconciling Vault","Request.Namespace":"vault","Request.Name":"vault"}
panic: runtime error: index out of range [5] with length 5

goroutine 779 [running]:
github.com/banzaicloud/bank-vaults/operator/pkg/controller/vault.createOrUpdateObjectWithClient({0x1a3a608, 0xc0000b3590}, {0x1a56bc8, 0xc004e3ea00})
	/build/operator/pkg/controller/vault/vault_controller.go:159 +0xb45
github.com/banzaicloud/bank-vaults/operator/pkg/controller/vault.(*ReconcileVault).createOrUpdateObject(...)
	/build/operator/pkg/controller/vault/vault_controller.go:127
github.com/banzaicloud/bank-vaults/operator/pkg/controller/vault.(*ReconcileVault).Reconcile(0xc00043fbf0, {0xc0006a8000, 0x15e2b60}, {{{0xc000c64a60, 0x16bb1c0}, {0xc000c64a50, 0xc0006a4880}}})
	/build/operator/pkg/controller/vault/vault_controller.go:310 +0x5b2
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0003a2280, {0x1a0bcb0, 0xc0006a8000}, {0x1644080, 0xc00067da80})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0-beta.5/pkg/internal/controller/controller.go:298 +0x303
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003a2280, {0x1a0bcb0, 0xc0006a8000})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0-beta.5/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0-beta.5/pkg/internal/controller/controller.go:214 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0-beta.5/pkg/internal/controller/controller.go:210 +0x354
```

**Expected behaviour**:
Operator pod should either not have this issue or gracefully handle error

**Steps to reproduce the bug**:
Deploy operator to vault-infra namespace per documented install instructions
Deploy Vault object to vault namespace

**Environment details**:
- Kubernetes version: 1.19
- Cloud-provider/provisioner: AWS
- bank-vaults version: 1.14.1, also tried 0.14.0
- Install method: Helm

/kind bug

**Additional context**:
Operator config 
```apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    meta.helm.sh/release-name: vault-operator
    meta.helm.sh/release-namespace: vault-infra
  labels:
    app.kubernetes.io/instance: vault-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault-operator
    helm.sh/chart: vault-operator-1.14.1
  name: vault-operator
  namespace: vault-infra
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-operator
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: vault-operator
        app.kubernetes.io/name: vault-operator
    spec:
      affinity: {}
      containers:
      - command:
        - vault-operator
        - -sync_period
        - 1m
        env:
        - name: WATCH_NAMESPACE
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: vault-operator
        - name: OPERATOR_LOG_LEVEL
          value: debug
        - name: BANK_VAULTS_IMAGE
          value: ghcr.io/banzaicloud/bank-vaults:1.14.1
        image: ghcr.io/banzaicloud/vault-operator:1.14.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: vault-operator
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8383
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: vault-operator
      serviceAccountName: vault-operator
      terminationGracePeriodSeconds: 10





Vault object config
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  labels:
    app.kubernetes.io/name: vault
    vault_cr: vault
  name: vault
  namespace: vault
spec:
  annotations:
    common/annotation: "true"
  caNamespaces:
  - '*'
  config:
    api_addr: https://vault.vault:8200
    cluster_addr: https://${.Env.POD_NAME}:8201
    listener:
    - tcp:
        address: 0.0.0.0:8300
        tls_cert_file: /etc/letsencrypt/tls.crt
        tls_key_file: /etc/letsencrypt/tls.key
    - tcp:
        address: 0.0.0.0:8200
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    storage:
      raft:
        path: /vault/file
    ui: true
  credentialsConfig:
    env: ""
    path: ""
    secretName: ""
  externalConfig:
    auth:
    - roles:
      - bound_service_account_names:
        - default
        - vault
        - vault-secrets-webhook
        bound_service_account_namespaces:
        - default
        - vault
        - vswh
        name: default
        policies: allow_secrets
        ttl: 1h
      type: kubernetes
    policies:
    - name: allow_secrets
      rules: path "secret/*" { capabilities = ["create", "read", "update", "delete",
        "list"] }
    secrets:
    - description: General secrets.
      options:
        version: 2
      path: secret
      type: kv
  image: vault:1.6.2
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target:
      ingress.kubernetes.io/protocol: https
      ingress.kubernetes.io/ssl-proxy-headers: 'X-Forwarded-Proto: https'
      ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/frontend-entry-points: http,https
      vault.security.banzaicloud.io/vault-addr: http://vault.vault:8200
      vault.security.banzaicloud.io/vault-skip-verify: "true"
    spec:
      rules:
      - host: 
  nodeAffinity: {}
  podAntiAffinity: failure-domain.beta.kubernetes.io/zone
  resources:
    vault:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 2Gi
  securityContext: {}
  serviceAccount: vault
  servicePorts:
    api-port: 8200
    cluster-port: 8201
    external-port: 8300
    https-port: 443
  serviceRegistrationEnabled: true
  serviceType: LoadBalancer
  size: 3
  statsdDisabled: true
  unsealConfig:
    kubernetes:
      secretNamespace: vault
    options:
      preFlightChecks: true
  vaultAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-internal: 172.23.0.0/16
    service.beta.kubernetes.io/aws-load-balancer-type: internal
    type/instance: vault
  vaultConfigurerAnnotations:
    type/instance: vaultconfigurer
  vaultConfigurerLabels:
    example.com/log-format: string
  vaultContainerSpec:
    name: ""
    resources: {}
  vaultEnvsConfig:
  - name: VAULT_LOG_LEVEL
    value: debug
  vaultLabels:
    example.com/log-format: json
  veleroEnabled: true
  volumeClaimTemplates:
  - metadata:
      name: vault-raft
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      volumeMode: Filesystem
  volumeMounts:
  - mountPath: /vault/file
    name: vault-raft
  - mountPath: /etc/letsencrypt
    name: vault-ingress-tls
  volumes:
  - name: vault-ingress-tls
    secret:
      defaultMode: 420
      secretName: vault-ingress-tls

**Comment by tabossert** [comment]
This seems to be an issue when I added an additional serviceport for https access, I removed the original externalport 8300 and now operator is no longer crashing.

**Comment by tabossert** [comment]
When I re-deployed with latest operator code locally, I couldn't reproduce issue as it added the additional port to the service.  It seems that if the service is deployed initially and a new port is added to existing Vault object, it doesn't update the service and thus it hits this range error since Vault expects 6, but only finds 5 when querying service.

**Comment by bonifaido** [comment]
I took the Vault CR example you have added to the issue but I neither could reproduce the issue with the most recent version of the operator.

**Comment by tabossert** [comment]
Thanks @bonifaido , I will see if it shows up again, it might have been some disconnect while I was working on getting the operator configured between it and the service.  At this point I will close this, and re-open if I see it again.
