### ISSUE TITLE
Kurun version 0.6.0 issues

### ISSUE THREAD

**Issue by akijakya** [banzaicloud/bank-vaults#1734]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:

When I try to run the webhook locally for testing purposes, I get issues related to `kurun`:

- The version mentioned in the title cannot be installed with Homebrew due to an obsolete `inlets` dependency
- Even after successful installation there is an invalid memory address panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1e483b3]

goroutine 1 [running]:
github.com/banzaicloud/kurun/internal/cmd.NewPortForwardCommand.func1(0xc0003fdb80, {0xc000510a80, 0x7, 0x7})
	/Users/nandork@cisco.com/Code/src/github.com/banzaicloud/kurun/internal/cmd/portforward.go:287 +0x1733
github.com/spf13/cobra.(*Command).execute(0xc0003fdb80, {0xc000510a10, 0x7, 0x7})
	/Users/nandork@cisco.com/Code/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003fd680)
	/Users/nandork@cisco.com/Code/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/nandork@cisco.com/Code/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
	/Users/nandork@cisco.com/Code/src/github.com/banzaicloud/kurun/main.go:13 +0x1e 
```

**Expected behaviour**:
A concise description of what you expected to happen.

Kurun can be installed via Homebrew and works properly

**Steps to reproduce the bug**:
Steps to reproduce the bug should be clear and easily reproducible to help people
gain an understanding of the problem.

`brew install banzaicloud/tap/kurun`

`make webhook up -j`

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.25.2
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Docker Desktop
- bank-vaults version (e.g. 0.4.17): 1.16.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): above
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by akijakya** [comment]
Fixed in https://github.com/banzaicloud/kurun/releases/tag/0.6.1 and https://github.com/banzaicloud/kurun/releases/tag/0.6.2
