### ISSUE TITLE
[vault-secrets-webhook] fails to use service account token on k8s 1.24

### ISSUE THREAD

**Issue by bramaq** [banzaicloud/bank-vaults#1738]
**Describe the bug**:
K8S 1.24 no longer generates a service account (SA) token upon SA creation. Hence when attempting to mutate a secret specifying the SA to use, it fails to load the token to send to vault. I believe this is due to code on [webhook.go line 216](https://github.com/banzaicloud/bank-vaults/blob/main/pkg/webhook/webhook.go#L216 ) which assumes the sa secrets is always populated:
`... sa.Secrets[0].Name ...`

This leads to a stacktrace in the webhook logs with a message like:
```
2022/12/06 13:52:00 http: panic serving 10.252.109.4:39180: runtime error: index out of range [0] with length 0
```
**Expected behaviour**:
Instead of trying to get the token via the service account secrets property, perhaps the token request api could be used to generate a short-lived token for this sa?
https://v1-24.docs.kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/

**Steps to reproduce the bug**:
- deploy the vault secrets webhook to k8s 1.24 using the helm chart
- configure the vault kubernetes endpoint to use the client jwt as the reviewer
- try mutating a secret specifying a SA:
```apiVersion: v1
kind: Secret
metadata:
  annotations:
    vault.security.banzaicloud.io/vault-role: test-role
    vault.security.banzaicloud.io/vault-serviceaccount: default
  name: test
  namespace: default
type: Opaque
stringData:
  test: vault:kv/data/foo#bar
 ```
 - get the logs from the webhook pods  

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.24):
- Cloud-provider/provisioner (EKS):
- bank-vaults secrets webhook version: 1.16.0
- Install method (e.g. helm or static manifests): helm 
- Logs from the misbehaving component (and any other relevant logs):
```+ banzai-vault-webhook-vault-secrets-webhook-858f754dc7-84ghk › vault-secrets-webhook
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook time="2022-12-05T22:05:12Z" level=info msg="Listening on https://:8443" app=vault-secrets-webhook
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook 2022/12/06 13:52:00 http: panic serving 10.252.109.4:39180: runtime error: index out of range [0] with length 0
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook goroutine 49257 [running]:
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook net/http.(*conn).serve.func1()
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook 	/usr/local/go/src/net/http/server.go:1850 +0xb8
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook panic({0x17f4720, 0x40006b26d8})
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook 	/usr/local/go/src/runtime/panic.go:890 +0x260
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook github.com/banzaicloud/bank-vaults/pkg/webhook.(*MutatingWebhook).newVaultClient(_, {{0x400005606b, 0x23}, {0x19290af, 0x3}, {0x4000691d10, 0x27}, {0x400005c04b, 0x2c}, 0x0, ...})
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook 	/build/pkg/webhook/webhook.go:216 +0x83c
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook github.com/banzaicloud/bank-vaults/pkg/webhook.(*MutatingWebhook).MutateSecret(_, _, {{0x400005606b, 0x23}, {0x19290af, 0x3}, {0x4000691d10, 0x27}, {0x400005c04b, 0x2c}, ...})
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook 	/build/pkg/webhook/secret.go:94 +0x6c
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook github.com/banzaicloud/bank-vaults/pkg/webhook.(*MutatingWebhook).VaultSecretsMutator(0x0?, {0x1d5dcb0, 0x400063e9c0}, 0x400024e4b0, {0x1d741e0?, 0x40002d6780?})
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook 	/build/pkg/webhook/webhook.go:60 +0xd8
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook github.com/banzaicloud/bank-vaults/pkg/webhook.ErrorLoggerMutator.func1({0x1d5dcb0, 0x400063e9c0}, 0xe8?, {0x1d741e0?, 0x40002d6780?})
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook 	/build/pkg/webhook/webhook.go:273 +0x48
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook github.com/slok/kubewebhook/v2/pkg/webhook/mutating.MutatorFunc.Mutate(0x40002d6780?, {0x1d5dcb0?, 0x400063e9c0?}, 0x4a9944?, {0x1d741e0?, 0x40002d6780?})
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook 	/go/pkg/mod/github.com/slok/kubewebhook/v2@v2.1.0/pkg/webhook/mutating/mutator.go:45 +0x48
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook github.com/slok/kubewebhook/v2/pkg/webhook/mutating.mutatingWebhook.mutatingAdmissionReview({{_, _}, {_, _}, {_, _}, {{_, _}, {_, _}, ...}, ...}, ...)
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook 	/go/pkg/mod/github.com/slok/kubewebhook/v2@v2.1.0/pkg/webhook/mutating/webhook.go:116 +0xe0
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook github.com/slok/kubewebhook/v2/pkg/webhook/mutating.mutatingWebhook.Review({{_, _}, {_, _}, {_, _}, {{_, _}, {_, _}, ...}, ...}, ...)
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook 	/go/pkg/mod/github.com/slok/kubewebhook/v2@v2.1.0/pkg/webhook/mutating/webhook.go:104 +0x1e4
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook github.com/slok/kubewebhook/v2/pkg/webhook.measuredWebhook.Review({{0x1943ee8, _}, {_, _}, {_, _}, {_, _}}, {_, _}, ...)
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook 	/go/pkg/mod/github.com/slok/kubewebhook/v2@v2.1.0/pkg/webhook/metrics.go:114 +0x13c
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook github.com/slok/kubewebhook/v2/pkg/http.handler.ServeHTTP({{0x1d5d2a8?, 0x400047b940?}, {0x1d634e0?, 0x400048a850?}}, {0x1d5cd08, 0x400052c540}, 0x4000220f00)
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook 	/go/pkg/mod/github.com/slok/kubewebhook/v2@v2.1.0/pkg/http/handler.go:129 +0x700
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook net/http.(*ServeMux).ServeHTTP(0x400069063e?, {0x1d5cd08, 0x400052c540}, 0x4000220f00)
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook 	/usr/local/go/src/net/http/server.go:2487 +0x140
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook net/http.serverHandler.ServeHTTP({0x1d51050?}, {0x1d5cd08, 0x400052c540}, 0x4000220f00)
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook 	/usr/local/go/src/net/http/server.go:2947 +0x2cc
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook net/http.(*conn).serve(0x40001adcc0, {0x1d5dcb0, 0x40001f0120})
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook 	/usr/local/go/src/net/http/server.go:1991 +0x544
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook created by net/http.(*Server).Serve
banzai-vault-webhook-vault-secrets-webhook-858f754dc7-c5sx5 vault-secrets-webhook 	/usr/local/go/src/net/http/server.go:3102 +0x43c
```
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by bramaq** [comment]
All, I have a working version of this that I hope to contribute somewhere this week.

**Comment by sergeyshevch** [comment]
@akijakya When do you expect this fix to be released? I also faced with same issue in one of my cluster after 1.24 upgrade

**Comment by akijakya** [comment]
Hi @sergeyshevch, we are just preparing a release, thanks for your patience! 🙂

**Comment by sergeyshevch** [comment]
@akijakya We need to add the next rules to the helm RBAC template to make it works.
```
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    verbs:
      - "create"
```
